version: '3.8'

services:
  postgres:
    build: .
    command: uvicorn todo-app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src/personalised_todo
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lzt25
      - POSTGRES_DB=postgres
    expose:
      - 5432

volumes:
  postgres_data:

networks:
     - backend